# *** agi, int, and spr removed because they seem to all be set to
# '0' by default

common:
  hp: 2   
  atk: 1.5    
  def: 1   
  luck: 1.2  
  defMag: 1
  offMag: 1
  # ------------------- #
  # THESE ARE HIGHLY EXPERIMENTAL AND HAVEN'T BEEN TESTED
  # Leave at 1 unless you want to test their effects for yourself :)
  downDurable: 1
  guardDurable: 1
  actionEnable: 1
  # ------------------- #
  exp: 1
  dropSpp: 1
  itemDrop1: 1
  itemDrop2: 1
  itemDrop3: 1
  # ------------------- #
  DropLuc: 1
  KnockOutDropSpp: 1
  LAttackDropSpp: 1
  ChargeAttackDropSpp: 1

boss:
  hp: 2   
  atk: 1.5    
  def: 1   
  luck: 1.2  
  defMag: 1
  offMag: 1
  # ------------------- #
  # THESE ARE HIGHLY EXPERIMENTAL AND HAVEN'T BEEN TESTED
  # Leave at 1 unless you want to test their effects for yourself :)
  downDurable: 1
  guardDurable: 1
  actionEnable: 1
  # ------------------- #
  exp: 1
  dropSpp: 1
  itemDrop1: 1
  itemDrop2: 1
  itemDrop3: 1
  # ------------------- #
  DropLuc: 1
  KnockOutDropSpp: 1
  LAttackDropSpp: 1
  ChargeAttackDropSpp: 1   

shinju:
  hp: 2   
  atk: 1.5    
  def: 1   
  luck: 1.2  
  defMag: 1
  offMag: 1
  # ------------------- #
  # THESE ARE HIGHLY EXPERIMENTAL AND HAVEN'T BEEN TESTED
  # Leave at 1 unless you want to test their effects for yourself :)
  downDurable: 1
  guardDurable: 1
  actionEnable: 1
  # ------------------- #
  exp: 1
  dropSpp: 1
  itemDrop1: 1
  itemDrop2: 1
  itemDrop3: 1
  # ------------------- #
  DropLuc: 1
  KnockOutDropSpp: 1
  LAttackDropSpp: 1
  ChargeAttackDropSpp: 1   

parts:
  hp: 2   
  atk: 1.5    
  def: 1   
  luck: 1.2  
  defMag: 1
  offMag: 1
  # ------------------- #
  # THESE ARE HIGHLY EXPERIMENTAL AND HAVEN'T BEEN TESTED
  # Leave at 1 unless you want to test their effects for yourself :)
  downDurable: 1
  guardDurable: 1
  actionEnable: 1
  # ------------------- #
  exp: 1
  dropSpp: 1
  itemDrop1: 1
  itemDrop2: 1
  itemDrop3: 1
  # ------------------- #
  DropLuc: 1
  KnockOutDropSpp: 1
  LAttackDropSpp: 1
  ChargeAttackDropSpp: 1   