common:
  hp: 2   
  atk: 1.5    
  def: 1   
  agi: 1.2   
  int: 1.5  
  spr: 1.5 
  luck: 1.2  
  defMag: 1
  offMag: 1
  exp: 1   

boss:
  hp: 2   
  atk: 1.5    
  def: 1   
  agi: 1.2   
  int: 1.5  
  spr: 1.5 
  luck: 1.2  
  defMag: 1
  offMag: 1
  exp: 1   

shinju:
  hp: 2   
  atk: 1.5    
  def: 1   
  agi: 1.2   
  int: 1.5  
  spr: 1.5 
  luck: 1.2  
  defMag: 1
  offMag: 1
  exp: 1   

parts:
  hp: 2   
  atk: 1.5    
  def: 1   
  agi: 1.2   
  int: 1.5  
  spr: 1.5 
  luck: 1.2  
  defMag: 1
  offMag: 1
  exp: 1   