common:
  hp: 0        #  Starting offset for finding stats  
  atk: 87      # 29 * 3
  def: 116     # 29 * 4
  # agi: 145     # 29 * 5
  # int: 174     # 29 * 6
  # spr: 203     # 29 * 7
  luck: 232    # 29 * 8
  defMag: 261  # 29 * 9
  offMag: 290  # 29 * 10
  downDurable: 319  # 29 * 11  #** This is a float number, needs to be accounted for
  guardDurable: 377  # 29 * 13  # float number
  # actionEnable: 418  # 29 * 15   # ORIGINAL PRETEST VALUE WAS 453
  # ------------------- #
  exp: 822     # Can't use the same pattern for exp
  dropSpp: 851  # 822 + 29
  itemDrop1: 953
  itemDrop2: 957
  itemDrop3: 961
  # ------------------- #
  DropLuc: 990
  KnockOutDropSpp: 1048
  LAttackDropSpp: 1077
  ChargeAttackDropSpp: 1106

# Currently all of these offsets are the same 
# for these different types of enemies
# But for generality, we will keep them separate
boss:
  hp: 0        #  Starting offset for finding stats  
  atk: 87      # 29 * 3
  def: 116     # 29 * 4
  # agi: 145     # 29 * 5
  # int: 174     # 29 * 6
  # spr: 203     # 29 * 7
  luck: 232    # 29 * 8
  defMag: 261  # 29 * 9
  offMag: 290  # 29 * 10
  downDurable: 319  # 29 * 11  #** This is a float number, needs to be accounted for
  guardDurable: 377  # 29 * 13  # float number
  # actionEnable: 418  # 29 * 15
  # ------------------- #
  exp: 822     # Can't use the same pattern for exp
  dropSpp: 851  # 822 + 29
  itemDrop1: 953
  itemDrop2: 957
  itemDrop3: 961
  # ------------------- #
  DropLuc: 990
  KnockOutDropSpp: 1048
  LAttackDropSpp: 1077
  ChargeAttackDropSpp: 1106

shinju:
  hp: 0        #  Starting offset for finding stats  
  atk: 87      # 29 * 3
  def: 116     # 29 * 4
  # agi: 145     # 29 * 5
  # int: 174     # 29 * 6
  # spr: 203     # 29 * 7
  luck: 232    # 29 * 8
  defMag: 261  # 29 * 9
  offMag: 290  # 29 * 10
  downDurable: 319  # 29 * 11  #** This is a float number, needs to be accounted for
  guardDurable: 377  # 29 * 13  # float number
  # actionEnable: 418  # 29 * 15
  # ------------------- #
  exp: 822     # Can't use the same pattern for exp
  dropSpp: 851  # 822 + 29
  itemDrop1: 953
  itemDrop2: 957
  itemDrop3: 961
  # ------------------- #
  DropLuc: 990
  KnockOutDropSpp: 1048
  LAttackDropSpp: 1077
  ChargeAttackDropSpp: 1106

parts:
  hp: 0        #  Starting offset for finding stats  
  atk: 87      # 29 * 3
  def: 116     # 29 * 4
  # agi: 145     # 29 * 5
  # int: 174     # 29 * 6
  # spr: 203     # 29 * 7
  luck: 232    # 29 * 8
  defMag: 261  # 29 * 9
  offMag: 290  # 29 * 10
  downDurable: 319  # 29 * 11  #** This is a float number, needs to be accounted for
  guardDurable: 377  # 29 * 13  # float number
  # actionEnable: 435  # 29 * 15
  # ------------------- #
  exp: 822     # Can't use the same pattern for exp
  dropSpp: 851  # 822 + 29
  itemDrop1: 953
  itemDrop2: 957
  itemDrop3: 961
  # ------------------- #
  DropLuc: 990
  KnockOutDropSpp: 1048
  LAttackDropSpp: 1077
  ChargeAttackDropSpp: 1106

# Issue that エンプレスビー brought up with its data structure
exception:
  hp: 0        
  atk: 87      
  def: 116     
  luck: 232    
  defMag: 261  
  offMag: 290  
  downDurable: 319  
  guardDurable: 377  
  
  # ------------------- #
  exp: 822     
  dropSpp: 851  
  itemDrop1: 953
  itemDrop2: 957
  itemDrop3: 961
  # ------------------- #
  DropLuc: 990
  KnockOutDropSpp: 1012
  LAttackDropSpp: 1041
  ChargeAttackDropSpp: 1070